apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-web
spec:
  selector:
   matchLabels:
    app: testing-web
  replicas: 2
  template:
    metadata:
      labels:
        app: testing-web
    spec:
      containers:
        - name: test-web
          image: bverad/testing-web:latest
          ports:
          - containerPort: 8085
---
kind: Service
apiVersion: v1
metadata:
  name: testing-web
  labels:
    app: testing-web
spec:   
  type: LoadBalancer
  ports:
  - port: 8085
    targetPort: 8085
  selector:
   app: testing-web
