name: Pipeline to devops foundation course
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with maven
        run: | 
          mvn clean install -Dmaven.test.skip=true
          ls -lt

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copia de Jar a Raiz de proyecto
        run: |
          cd target
          ls -lt
          cp $GITHUB_WORKSPACE/build/libs/testing-web-complete-0.0.1-SNAPSHOT .
          chmod 777 testing-web-complete-0.0.1-SNAPSHOT.jar
          ls -lt 
      
      - name: Docker Build
        run: | 
          docker build --tag bverad/testing-web-complete:latest .
          docker images

      - name: Docker Push
        run: |
          docker push clagosu/testing-web-complete 

  automated-test:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Coverage per Test Execution
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test

      - name: Upload target folder
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: |
            ${{ github.workspace }}/target
            ${{ github.workspace }}/reports

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: ${{ github.workspace }}/target/surefire-reports/*.xml
          reporter: java-junit




